name: "HA Component CI"
description: "General purpose CI for formatting and validating Home Assistant custom components."
inputs:
  github_token:
    description: 'Your personal GitHub access token, the GitHub provided one should work just fine.'
    required: false
  format_code:
    description: 'Whether or not to format code, set to DISABLED to disable.'
    required: false
  hassfest:
    description: 'Whether or not to run hassfest, set to DISABLED to disable.'
    required: false
  flake8_fails:
    description: 'Customize error codes for flake8 that cause the run to fail, defaults to E9,F63,F7,F82.'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        # Installation
        git config --global pull.rebase false
        cp -rT ${{ github.action_path }} /home/runner/work/myaction
        python3 ${{ github.action_path }}/handle_install.py
      shell: bash
      name: Downloads
    - run: |
        # Validation
        python3 ${{ github.action_path }}/validate_code.py
      shell: bash
      name: Validation
    - run: |
        # Formatting
        python3 ${{ github.action_path }}/format_code.py
      shell: bash
      name: Formatting
branding:
  icon: 'home'
  color: 'blue'
