name: "HA Component CI"
description: "General purpose CI for formatting and validating Home Assistant custom components."
inputs:
  github_token:
    description: 'Your personal GitHub access token, the GitHub provided one should work just fine.'
    required: true
  format_code:
    description: 'Whether or not to format code, set to DISABLED to disable.'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        # Installation
        cp -rT ${{ github.action_path }} /home/runner/work/myaction
        python3 ${{ github.action_path }}/handle_install.py
      shell: bash
      name: Downloads
    - run: |
        # Validation
        python3 ${{ github.action_path }}/validate_code.py
      shell: bash
      name: Validation
    - run: |
        # Formatting
        git pull
        git add .
        git reset --hard
        python3 ${{ github.action_path }}/format_code.py
      shell: bash
      name: Validation
branding:
  icon: 'home'
  color: 'blue'
