name: "HA Component CI"
description: "General purpose CI for formatting and validating Home Assistant custom components."
inputs:
  github_token:
    description: 'Your personal GitHub Access token, just set it to \${{ secrets.GITHUB_TOKEN }}'
    required: true
  format_code:
    description: 'Whether or not to format code, set to DISABLED to disable'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        # Installation
        pwd
        cd ~
        pwd
        cd ${{ github.action_path }}
        pwd
        cd ${{ github.workspace }}
        pwd
        python3 ${{ github.action_path }}/handle_install.py
      shell: bash
      name: Downloads
    - run: |
        # Validation
        python3 ${{ github.action_path }}/validate_code.py
      shell: bash
      name: Validation
    - run: |
        # Formatting
        git add .
        git reset --hard
        python3 ${{ github.action_path }}/format_code.py
        sh ${{ github.action_path }}/push_code.sh
      shell: bash
      name: Validation
branding:
  icon: 'home'
  color: 'blue'
